# Generated by Django 4.0.6 on 2022-08-08 09:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
