# Generated by Django 4.0.6 on 2022-08-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_alter_noticia_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='resumen',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
