# Generated by Django 4.0.6 on 2022-08-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_noticia_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='user',
            new_name='usuario',
        ),
    ]
