# Generated by Django 4.0.6 on 2022-08-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_noticia_resumen'),
        ('noticia', '0004_rename_user_noticia_usuario'),
    ]

    operations = [
    ]
