# Generated by Django 4.0.6 on 2022-08-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0005_merge_20220825_1449'),
        ('noticia', '0005_merge_20220825_1900'),
    ]

    operations = [
    ]
