# Generated by Django 4.0.6 on 2022-08-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrousel',
            name='title',
            field=models.CharField(default='titulo', max_length=150),
        ),
    ]
