# Generated by Django 4.0.6 on 2022-08-27 05:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrousel', '0002_carrousel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrousel',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen'),
        ),
    ]
