# Generated by Django 4.0.6 on 2022-08-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_alter_noticia_texto'),
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='noticia.noticia'),
        ),
    ]
